#!/bin/bash
# GitHub PR Creator plugin — on-event handler
# Creates a GitHub PR when chain-completed fires.
# Env vars: PLUGIN_TOKEN, PLUGIN_OWNER, PLUGIN_REPO, PLUGIN_BASE_BRANCH,
#           PLUGIN_DRAFT, PLUGIN_CHAIN_ID, PLUGIN_RUN_ID

set -euo pipefail

TOKEN="${PLUGIN_TOKEN:-}"
OWNER="${PLUGIN_OWNER:-}"
REPO="${PLUGIN_REPO:-}"
BASE_BRANCH="${PLUGIN_BASE_BRANCH:-main}"
DRAFT="${PLUGIN_DRAFT:-false}"
CHAIN_ID="${PLUGIN_CHAIN_ID:-unknown}"
RUN_ID="${PLUGIN_RUN_ID:-}"

if [[ -z "$TOKEN" || -z "$OWNER" || -z "$REPO" ]]; then
    echo "  [github-pr] error: PLUGIN_TOKEN, PLUGIN_OWNER, PLUGIN_REPO required"
    exit 1
fi

# get current branch
HEAD_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
if [[ -z "$HEAD_BRANCH" || "$HEAD_BRANCH" == "HEAD" || "$HEAD_BRANCH" == "$BASE_BRANCH" ]]; then
    echo "  [github-pr] skipping: not on a feature branch (current=$HEAD_BRANCH, base=$BASE_BRANCH)"
    exit 0
fi

# check if branch has commits ahead of base
AHEAD=$(git rev-list --count "${BASE_BRANCH}..${HEAD_BRANCH}" 2>/dev/null || echo "0")
if [[ "$AHEAD" -eq 0 ]]; then
    echo "  [github-pr] skipping: no commits ahead of $BASE_BRANCH"
    exit 0
fi

# check if PR already exists for this branch
EXISTING=$(curl -s \
    -H "Authorization: Bearer $TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/${OWNER}/${REPO}/pulls?head=${OWNER}:${HEAD_BRANCH}&state=open" \
    2>/dev/null | jq 'length' 2>/dev/null || echo "0")

if [[ "$EXISTING" -gt 0 ]]; then
    echo "  [github-pr] PR already open for branch $HEAD_BRANCH — skipping"
    exit 0
fi

# build PR title + body
PR_TITLE="[mentiko] Chain '${CHAIN_ID}' output — ${HEAD_BRANCH}"
PR_BODY="This PR was automatically created by the Mentiko **github-pr** plugin after chain **\`${CHAIN_ID}\`** completed.

**Branch:** \`${HEAD_BRANCH}\` → \`${BASE_BRANCH}\`${RUN_ID:+
**Run ID:** \`${RUN_ID}\`}

---
*Generated by [mentiko](https://mentiko.com) chain runner*"

# create the PR
RESPONSE=$(curl -s -X POST \
    -H "Authorization: Bearer $TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -H "Content-Type: application/json" \
    "https://api.github.com/repos/${OWNER}/${REPO}/pulls" \
    -d "$(jq -nc \
        --arg title "$PR_TITLE" \
        --arg body "$PR_BODY" \
        --arg head "$HEAD_BRANCH" \
        --arg base "$BASE_BRANCH" \
        --argjson draft "$([ "$DRAFT" = "true" ] && echo true || echo false)" \
        '{title:$title, body:$body, head:$head, base:$base, draft:$draft}')" \
    2>/dev/null)

PR_URL=$(echo "$RESPONSE" | jq -r '.html_url // ""' 2>/dev/null)
PR_NUMBER=$(echo "$RESPONSE" | jq -r '.number // ""' 2>/dev/null)

if [[ -n "$PR_URL" ]]; then
    echo "  [github-pr] created PR #${PR_NUMBER}: $PR_URL"
else
    ERROR=$(echo "$RESPONSE" | jq -r '.message // "unknown error"' 2>/dev/null)
    echo "  [github-pr] error: $ERROR"
    exit 1
fi
