#!/bin/bash
# Email Digest plugin — on-event handler
# Accumulates events in a JSONL buffer file and flushes when threshold is hit.
# Env vars: PLUGIN_TO, PLUGIN_DIGEST_FILE, PLUGIN_SEND_AFTER_EVENTS,
#           PLUGIN_EVENT_TYPE, PLUGIN_CHAIN_ID, PLUGIN_RUN_ID, BETTER_AUTH_URL

set -euo pipefail

TO="${PLUGIN_TO:-}"
DIGEST_FILE="${PLUGIN_DIGEST_FILE:-/tmp/mentiko-digest.jsonl}"
SEND_AFTER="${PLUGIN_SEND_AFTER_EVENTS:-10}"
EVENT_TYPE="${PLUGIN_EVENT_TYPE:-unknown}"
CHAIN_ID="${PLUGIN_CHAIN_ID:-unknown}"
RUN_ID="${PLUGIN_RUN_ID:-}"
BASE_URL="${BETTER_AUTH_URL:-http://localhost:3000}"

if [[ -z "$TO" ]]; then
    echo "  [email-digest] error: PLUGIN_TO not set"
    exit 1
fi

# append event to buffer
cat >> "$DIGEST_FILE" <<EOF
{"event":"${EVENT_TYPE}","chain":"${CHAIN_ID}","run":"${RUN_ID}","ts":"$(date -Iseconds 2>/dev/null || date -u +"%Y-%m-%dT%H:%M:%SZ")"}
EOF

# count buffered events
event_count=$(wc -l < "$DIGEST_FILE" 2>/dev/null || echo "0")
event_count="${event_count// /}"

# only flush if threshold reached
if [[ "$SEND_AFTER" -gt 0 && "$event_count" -lt "$SEND_AFTER" ]]; then
    echo "  [email-digest] buffered ($event_count/${SEND_AFTER})"
    exit 0
fi

# build digest summary
summary=$(while IFS= read -r line; do
    e=$(echo "$line" | jq -r '.event // "?"' 2>/dev/null)
    c=$(echo "$line" | jq -r '.chain // "?"' 2>/dev/null)
    t=$(echo "$line" | jq -r '.ts // "?"' 2>/dev/null)
    echo "  • [$t] $c — $e"
done < "$DIGEST_FILE")

subject="[mentiko] Chain digest — $event_count events"
body="Mentiko chain activity digest:\n\n${summary}\n\n---\nGenerated by mentiko email-digest plugin"

# send via web API
curl -s -X POST "${BASE_URL}/api/email/send" \
    -H "Content-Type: application/json" \
    -d "$(jq -nc --arg to "$TO" --arg subject "$subject" --arg body "$body" \
        '{to:$to, subject:$subject, text:$body}')" \
    > /dev/null 2>&1 || true

# clear buffer after sending
> "$DIGEST_FILE"
echo "  [email-digest] sent digest ($event_count events)"
